@{
    SchemaVersion = '1.0'
    ResearchDate = '2026-09-06'
    # Reviewed against the actual probe branches, not inferred from the monitor display name.
    StateReasons = @{
        'FabricDeviceState' = 'Good when any configured management TCP port accepts a connection; Warning when only ICMP responds; Critical when neither responds or the probe throws. Missing management address yields NotApplicable. With local-ipmi, presence of a Microsoft_IPMI provider instance gives Good and absence gives Warning; no sensor readings are evaluated. These are management-path observations, not authenticated API, hardware-sensor or data-plane health. Check expected ports, ACLs, routing and vendor telemetry before diagnosing a device failure.'
        'HyperVPrivateCloud.Host.VMMS.Monitor' = 'Good: vmms is Running. Critical: the service is missing or not Running. No native Warning branch. Running VMs can continue despite a management-service failure; check Get-Service vmms and VMMS events before an approved repair.'
        'HyperVPrivateCloud.Host.VmCompute.Monitor' = 'Good: vmcompute is Running. Critical: the service is missing or not Running. No native Warning branch. Identify dependent compute/container operations and service events; do not equate this with proof that all Hyper-V VMs stopped.'
        'HyperVPrivateCloud.Host.PowerShell.Monitor' = 'Good: the Hyper-V module and Get-VMHost command are available. Critical: that prerequisite is unavailable. This impairs monitoring; it does not independently prove a VM outage. Check the probe runtime, module installation and first error.'
        'HyperVPrivateCloud.Host.Hypervisor.Monitor' = 'Good: Win32_ComputerSystem.HypervisorPresent is true after Get-VMHost succeeds. Critical: it is false or prerequisites failed. Verify the hardware/boot/Hyper-V configuration and event evidence; any boot configuration change or restart requires a maintenance plan. No native Warning branch.'
        'HyperVPrivateCloud.Host.Cpu.Monitor' = 'Critical when observed hypervisor processor utilization is at least CpuCriticalPercent; otherwise Warning at least CpuWarningPercent, otherwise Good. Compare host processor load and VM placement over time. These thresholds differ from the separate logical/root/guest processor monitors; use this monitor configuration, not another monitor value.'
        'HyperVPrivateCloud.Host.Memory.Monitor' = 'Critical when available physical memory MB is at most MemoryCriticalMB; otherwise Warning at most MemoryWarningMB, otherwise Good. Inspect available capacity, VM allocations and failover reserve before placement or capacity changes.'
        'HyperVPrivateCloud.Host.Paging.Monitor' = 'Critical when Pages Input/sec is at least PagesInputCriticalPerSecond; otherwise Warning at least PagesInputWarningPerSecond, otherwise Good. An unavailable counter yields NotApplicable, not zero paging. Correlate sustained paging with available memory and storage latency; a single spike does not establish memory exhaustion.'
        'HyperVPrivateCloud.Host.VirtualMachines.Monitor' = 'Critical if any VM with AutomaticStartAction=Start is not Running, Starting, Stopping, Saving, Pausing or Resuming. Otherwise Good; no native Warning branch. This host summary uses auto-start policy; the runtime availability monitor also considers cluster ownership policy. Compare the named VM with its intended operating state before starting anything.'
        'HyperVPrivateCloud.Host.Checkpoints.Monitor' = 'Uses the oldest checkpoint age across host VMs, rounded to 0.1 hour. Critical at or above CheckpointCriticalHours; otherwise Warning at or above CheckpointWarningHours; otherwise Good. No checkpoints gives age zero. Verify retention intent, checkpoint owner and backing-volume headroom; use supported backup/Hyper-V cleanup, never manual AVHDX deletion.'
        'HyperVPrivateCloud.Host.Replication.Monitor' = 'Critical if any returned replication relationship reports native Health=Critical; otherwise Warning if any reports Warning; otherwise Good. A host with no returned relationships is Good here and is not thereby protected. Inspect the specific VM relationship, lag and recovery objective.'
        'HyperVPrivateCloud.Host.VirtualSwitches.Monitor' = 'Critical when an External virtual switch has no NetAdapterInterfaceDescriptions entries. Otherwise Good; no native Warning branch. This configuration check does not prove uplink link-state or forwarding health. Inspect the exact switch and physical adapter before an approved binding repair.'
        'HyperVPrivateCloud.Host.StorageAttachments.Monitor' = 'Critical when an enumerated VM disk with a path fails Test-Path -PathType Leaf or cannot be read by Get-VHD. Otherwise Good; no native Warning branch. Validate the path on the owner with the collector identity and storage provider before assuming data loss. This is attachment access, not a filesystem integrity check inside the guest.'
        'HyperVPrivateCloud.Host.DomainHealth.Monitor' = 'Good when the domain secure channel succeeds, or the computer is a workgroup member. Critical when the domain secure channel test returns false. Warning when domain evaluation throws. A workgroup Good result is not an AD health test; never repair trust or rejoin a cluster node without the directory owner.'
        'HyperVPrivateCloud.Host.DnsHealth.Monitor' = 'Good when the configured probe name resolves using the host resolver path. Critical when the resolution attempt fails. Warning when no DNS servers are configured on active adapters or DNS evaluation throws. Record the exact name, configured servers and collector; this does not test every DNS zone.'
        'HyperVPrivateCloud.Host.DeploymentService.Monitor' = 'Good when locally installed WDSServer is Running; Warning when installed but not Running. Absent WDS or an unprobeable optional WDS service yields NotApplicable. There is no ordinary Critical service-state branch. This local service check does not validate a complete PXE deployment transaction.'
        'HyperVPrivateCloud.Host.DhcpService.Monitor' = 'Good when the local DHCP Server service is Running; Warning when installed but not Running. An absent or unprobeable optional local DHCP service yields NotApplicable. There is no ordinary Critical service-state branch. Lease capacity, authorization and relay transactions require additional DHCP evidence.'
        'HyperVPrivateCloud.Host.Pipeline.Monitor' = 'Good means the host probe reached completion and supplies its UTC completion time. Critical means the probe failed before this state was set. No native Warning branch. Facets already sampled can retain their actual result while later unevaluated facets report the exception; inspect the first error and require a fresh successful run.'
        'HyperVPrivateCloud.VmRuntime.Availability.Monitor' = 'Critical for any Hyper-V VM state ending in Critical, regardless of expected power policy. Otherwise Critical if expected Running but actual state is not Running; Good when expected Running and actual Running. Other power policies yield NotApplicable. The all-VM collector derives expected Running from AutomaticStartAction=Start, currently-running StartIfRunning, or an Online clustered role (and a running clustered VM when role lookup is unavailable). No native Warning branch. Verify storage and intended power policy before starting or resuming a VM.'
        'HyperVPrivateCloud.VmRuntime.Heartbeat.Monitor' = 'For a running VM: Warning when no enabled Heartbeat integration service is returned; Good when its PrimaryStatusDescription matches OK; otherwise Critical. A non-running VM yields NotApplicable. Check guest integration support and actual guest responsiveness with its owner; this is not an application transaction check and does not require a guest SCOM agent.'
        'HyperVPrivateCloud.VmRuntime.IntegrationServices.Monitor' = 'For a running VM: Warning if any enabled integration service has a PrimaryStatusDescription that does not match OK; otherwise Good. Non-running VMs yield NotApplicable. No ordinary Critical status branch. Identify the individual enabled service and its guest prerequisites; zero returned services alone is not an exhaustive healthy guest test.'
        'HyperVPrivateCloud.VmRuntime.Checkpoints.Monitor' = 'Uses the oldest checkpoint for this VM, rounded to 0.1 hour. Critical at or above CheckpointCriticalHours; otherwise Warning at or above CheckpointWarningHours; otherwise Good. No checkpoints gives age zero. Correlate checkpoint age with approved backup/retention policy and storage headroom before supported cleanup.'
        'HyperVPrivateCloud.VmRuntime.Replication.Monitor' = 'Critical if any returned relationship for this VM reports native Health=Critical; otherwise Warning if any reports Warning; Good for remaining returned relationships. No relationship yields NotApplicable, not protected. Confirm current replication direction, lag, last success and the recovery objective before approved repair.'
        'HyperVPrivateCloud.VmRuntime.Storage.Monitor' = 'Critical when an enumerated disk with a path is missing as a leaf file or Get-VHD cannot read it; otherwise Good. No ordinary Warning branch. Check the named attachment, owner, path, storage availability and collector access; never recreate a disk or remove a checkpoint chain merely to clear this state.'
        'HyperVPrivateCloud.VmRuntime.Network.Monitor' = 'Warning when a VM adapter has no SwitchName or its status is outside Ok, Degraded and the empty string. Otherwise Good; no ordinary Critical status branch. This probe explicitly tolerates Degraded and does not test guest IP or application connectivity. Validate intended disconnection and the exact virtual-switch mapping before changing it.'
        'HyperVPrivateCloud.VmRuntime.MemoryPressure.Monitor' = 'Only applies to a running VM with DynamicMemoryEnabled. MemoryStatus matching Low or Warning yields Warning; otherwise matching Critical yields Critical; otherwise Good. Other VMs yield NotApplicable. Compare assigned memory, demand, maximum and host reserve before changing allocation; the numeric memory-pressure monitors provide separate capacity signals.'
        'HyperVPrivateCloud.VmRuntime.Pipeline.Monitor' = 'Good means VM evaluation completed, including a benign no-longer-local result during migration. Critical means collection failed; no native Warning branch. The departed VM is NotApplicable for workload facets and should be rediscovered on its new owner. Match stable VMId and current runtime ownership before treating an old runtime as a workload failure.'
    }
    Classes = @{
        'HyperVPrivateCloud.Boundary' = 'Stable cluster or standalone-host discovery boundary. It scopes membership and identity; use the associated Service DA for operational health rather than treating the boundary identifier as a workload.'
        'HyperVPrivateCloud.HostRole' = 'Hyper-V role hosted on a managed Windows computer. It owns host probes and host-derived VM discovery; host health can include capability dependencies, so drill into its actual leaf monitor before attributing a red Compute branch to CPU hardware.'
        'HyperVPrivateCloud.VirtualMachine' = 'Stable VM identity that survives host migration. Workload-guest SCOM agents are not required. The current VirtualMachineRuntime instance supplies owner-specific observations; this object does not prove application health inside the guest.'
        'HyperVPrivateCloud.VirtualMachineRuntime' = 'Current host-owned execution context of a VM. Runtime ownership changes with placement; use VMId and the current host together. An old runtime or stale discovery is not a second independent VM failure.'
        'HyperVPrivateCloud.VirtualHardDisk' = 'Discovered virtual disk attachment/configuration identity. Trace the VM, host path and backing storage; appearing in inventory does not imply direct per-VHD filesystem or array health monitoring.'
        'HyperVPrivateCloud.VirtualNetworkAdapter' = 'Discovered VM network adapter and its connectivity mapping. Follow its VM runtime and switch/network dependencies; no guest IP stack or application reachability is inferred from adapter presence.'
        'HyperVPrivateCloud.VirtualSwitch' = 'Hyper-V virtual switch topology object. Its type, host and uplink association describe connectivity, while relevant host/network monitors provide health at their authored scope.'
        'HyperVPrivateCloud.ReplicationRelationship' = 'Discovered primary/replica relationship for a VM. It represents disaster-recovery topology; read replication monitors and current native replication evidence for protection health.'
        'HyperVPrivateCloud.MonitoringPipeline' = 'Monitoring-path identity that helps locate collection and discovery problems. Inspect the actual pipeline monitors and last successful sample; a missing pipeline must not be interpreted as a healthy unmonitored host.'
        'HyperVPrivateCloud.Service' = 'Distributed application for one cluster, standalone host or VMM fabric boundary. It aggregates component health by aspect and is not itself a running Windows service.'
        'HyperVPrivateCloud.ComponentGroup' = 'Common component-group base used by the service model. Derived branches collect selected domain health; this abstract grouping is not a physical device or an independently probed service.'
        'HyperVPrivateCloud.ManagementComponent' = 'Management dependencies for the boundary, including authored host management, directory/DNS and optional VMM/SDN links. Management failure may prevent operations while already-running VMs remain available.'
        'HyperVPrivateCloud.ComputeComponent' = 'Host and compute infrastructure branch. Host aggregate dependencies can include management or storage prerequisites; follow the selected member monitor to distinguish compute pressure from a dependency failure.'
        'HyperVPrivateCloud.VirtualMachineComponent' = 'Host-observed VM runtime health branch. Power state, integration, disk, network and performance evidence are not a substitute for guest application monitoring.'
        'HyperVPrivateCloud.AvailabilityComponent' = 'Availability and clustering branch, including authored VM availability/replication signals and Microsoft cluster leaves. One failed clustered role can redden this branch without taking every node or VM down.'
        'HyperVPrivateCloud.StorageComponent' = 'Storage branch combining selected VM storage signals and installed storage capability/vendor dependencies. Follow a fault to its actual CSV, pool, host path or vendor source rather than assuming all storage failed.'
        'HyperVPrivateCloud.NetworkComponent' = 'Networking branch combining selected VM, host, physical-network and optional ATC/SDN/VMM network dependencies. Separate management endpoint reachability, control-plane configuration and tenant data-plane availability.'
        'HyperVPrivateCloud.MonitoringComponent' = 'Monitoring Pipeline branch for visibility and collection prerequisites. Unhealthy monitoring can invalidate confidence in old green workload states; repair telemetry and require fresh samples.'
        'HyperVPrivateCloud.Enterprise.Solution' = 'Singleton root named Hyper-V Private Cloud. It summarizes Hyper-V Fabric and Management Stack across discovered boundaries. A red root identifies a contributing dependency, not a total private-cloud outage.'
        'HyperVPrivateCloud.Enterprise.Fabric' = 'Singleton fabric DA containing discovered cluster, standalone and VMM service boundaries. Drill into the specific boundary and health aspect to determine impact.'
        'HyperVPrivateCloud.Enterprise.ManagementStack' = 'Singleton DA collecting boundary Management and Monitoring Pipeline components. Shared dependencies can legitimately appear here and under their fabric boundary; these are multiple impact paths, not necessarily duplicate incidents.'
        'HyperVPrivateCloud.ActiveDirectoryService' = 'Discovered directory dependency or configured service endpoint. Host secure-channel/DC-discovery observations are narrower than full Active Directory domain-controller health; use the AD team and native AD management pack for deeper assessment.'
        'HyperVPrivateCloud.DnsService' = 'Discovered DNS dependency or configured endpoint. A successful resolution/port check is scoped to the tested request and collector, not every zone or DNS client.'
        'HyperVPrivateCloud.DeploymentService' = 'Bare-metal deployment/PXE/WDS dependency. Loss can prevent provisioning without affecting running VMs. Only the authored service/endpoint checks are measured; a complete PXE boot transaction needs separate validation.'
        'HyperVPrivateCloud.PhysicalChassis' = 'Physical host enclosure or configured hardware-management endpoint. Basic reachability does not establish power, fan, temperature or drive health; hardware depth requires the vendor/native health source.'
        'HyperVPrivateCloud.TopOfRackSwitch' = 'Data-switch topology or configured endpoint used by the private-cloud network. Host uplink correlation and device health are separate evidence sources; a reachable management port does not prove every forwarding path works.'
        'HyperVPrivateCloud.OutOfBandSwitch' = 'Out-of-band management-switch dependency. Its failure can impair remote recovery while workload data networks remain operational; require device-side evidence for switch hardware/port health.'
        'HyperVPrivateCloud.EdgeFirewall' = 'Perimeter/firewall dependency or configured endpoint. TCP reachability does not test all firewall rules, HA state, routing or tenant egress; use the firewall vendor monitoring and a representative flow test.'
        'HyperVPrivateCloud.ConsoleServer' = 'Remote serial/console access dependency. Health describes the monitored management path, not the health of every attached device. Preserve alternative recovery access during changes.'
        'HyperVPrivateCloud.DhcpService' = 'Address-assignment dependency or configured endpoint. Service/port checks do not establish free leases, authorization or end-to-end relay behavior unless separately measured.'
        'HyperVPrivateCloud.Product.Group' = 'Product-scoping group for views and selection. Membership is not a separate service-level monitor and must not be mistaken for the main enterprise solution DA.'
        'HyperVPrivateCloud.Capability.Cluster.ClusterRole' = 'Cluster-wide collector identity hosted through the cluster core-group ownership path. It gathers node/quorum/network/group/CSV summaries; Microsoft cluster objects remain authoritative for their own resource-level health.'
        'HyperVPrivateCloud.Capability.FileServices.HostParticipation' = 'Host participation in SMB-backed VM storage. It gates SMB monitoring to relevant hosts and separates absent capability from a failed SMB query.'
        'HyperVPrivateCloud.Capability.FileServices.SmbShare' = 'SMB share identity used by the private-cloud topology. Match server and share, and distinguish client-observed access from native file-server service health.'
        'HyperVPrivateCloud.Capability.FileServices.SmbClientPath' = 'Client-to-SMB-server storage path. Its identity helps correlate sessions and multichannel paths; inspect the actual monitor target before treating a host-wide count as a path-specific failure.'
        'HyperVPrivateCloud.Capability.FileServices.SmbVhdxMapping' = 'Inventory mapping from VM virtual disk storage to an SMB path. It provides impact correlation, not an independent filesystem or guest-disk health probe.'
        'HyperVPrivateCloud.Capability.NetworkATC.NetworkIntent' = 'Network ATC intent defining the approved role and adapter configuration. Read desired settings and per-node convergence together; intention alone is not proof of applied state.'
        'HyperVPrivateCloud.Capability.NetworkATC.NetworkIntentNodeStatus' = 'Node-specific realization of an ATC intent. This identifies which host has provisioning, compliance or adapter readiness trouble when the same intent spans several nodes.'
        'HyperVPrivateCloud.Capability.NetworkATC.GlobalConfigurationStatus' = 'ATC global configuration/override observation. Compare the effective cluster-wide policy with the approved baseline before changing individual adapters.'
        'HyperVPrivateCloud.Capability.SDN.HostBinding' = 'Association between a Hyper-V host and the SDN authority. Service, identity, control/data-plane and certificate monitors apply only to a genuinely detected binding.'
        'HyperVPrivateCloud.Capability.Storage.HostParticipation' = 'Host participation in SAN/storage monitoring. It gates host-side storage workflows and helps distinguish unsupported or absent storage providers from failing storage.'
        'HyperVPrivateCloud.Capability.Storage.LogicalUnit' = 'Host-visible logical storage unit with stable storage identity. Correlate the LUN with array volume, host attachment and VM consumers; do not equate a host-view LUN with an independently monitored physical drive.'
        'HyperVPrivateCloud.Capability.Storage.HostAttachment' = 'A host attachment to a logical unit, including the host-side path and redundancy context. One host can lose a path while the same LUN remains accessible elsewhere.'
        'HyperVPrivateCloud.Capability.Storage.IscsiSession' = 'Host initiator session to an iSCSI target. Preserve session/target identity when evaluating connectivity, authentication and connection counts; avoid disrupting healthy peer sessions.'
        'HyperVPrivateCloud.Capability.Storage.FibreChannelPort' = 'Host HBA Fibre Channel port identity and supported provider observations. Correlate link/login/errors with the exact switch and array port before changing zoning or hardware.'
        'HyperVPrivateCloud.Capability.Storage.VirtualDiskMapping' = 'Inventory relationship connecting a VM disk to host-visible storage. It enables impact tracing; health must come from the relevant runtime, attachment/LUN or vendor monitor.'
        'HyperVPrivateCloud.Capability.VMM.LogicalNetwork' = 'VMM logical network describing connectivity policy and associated network sites. A missing site is a configuration problem, not proof that every existing VM network packet is failing.'
        'HyperVPrivateCloud.Capability.VMM.NetworkSite' = 'VMM network-site definition mapping VLAN/subnet policy and host scope. Validate its intended coverage and uplink association through VMM before making host-side changes.'
    }
    # Replace outdated original articles only where their semantics have been explicitly reviewed.
    Replacements = @{
        'HyperVPrivateCloud.Capability.Cluster.CSV.FreeSpace.Monitor' = @{
            Summary = 'Measures the lowest percentage of free partition capacity among the collected Cluster Shared Volumes. The detail identifies the worst volume. Low free capacity threatens growth of VM disks, checkpoint chains and replication/backup files; the specific impact depends on the consumers and their disk behavior.'
            Causes = 'Actual data growth, dynamic virtual disks, checkpoint chains, backup retention or replication backlog can consume free space. A thin-provisioned array or storage pool can also have a separate capacity constraint not represented by CSV filesystem free percentage.'
            Resolution = 'Use the named CSV and owner to identify its consumers and compare filesystem, pool and array capacity. Arrange supported expansion or owner-approved workload/storage placement changes. Checkpoint cleanup must use supported Hyper-V or backup workflows with the chain and recovery implications reviewed; never manually delete AVHDX files. Investigate replication backlog rather than resetting replication merely because HRL files are large. Verify headroom and the latest monitor sample after the approved change.'
        }
        'HyperVPrivateCloud.Capability.Cluster.Group.Failover.Monitor' = @{
            Name = 'Cluster role failure episodes'
            Summary = 'Counts local role failure episodes from System provider Microsoft-Windows-FailoverClustering events 1069, 1205 and 1254 within FailoverWindowHours. Named ResourceGroup fields correlate resource failures with their owning role; each role/five-minute bucket counts once. This is an approximate retry/failure indicator, not a count of ownership changes, VM migrations or cluster failovers. Event 1177 is not included.'
            Causes = 'A resource can repeatedly fail without ever moving. Examples include a missing VM configuration path, an inaccessible storage dependency, or a Replica Broker network name that cannot create its AD computer object. A five-minute bucket is an aggregation policy, not an assertion that each bucket contains exactly one incident. Only events retained on the current collector node are counted; owner changes and log retention can change observed coverage.'
            Resolution = 'Use GroupDetail to identify the role, current owner, recent resource error and UTC evidence. Inspect the first failing dependency before considering recovery. Preserve configured identity and thresholds. After the cause is repaired, current resource health can recover before the rolling failure count drops below its thresholds.'
        }
        'HyperVPrivateCloud.Capability.Cluster.Group.Failed.Monitor' = @{
            Summary = 'Counts cluster groups whose group-level state is Failed or PartialOnline. Offline is reported separately in detail and is not included in this count. A group can be Offline while one of its configuration resources is Failed; inspect native resource health and the Microsoft Cluster leaf monitors as well.'
            Causes = 'A dependent resource failed, a VM configuration or storage path is missing, or restart/failover attempts were exhausted. The parent group state alone does not identify which resource caused the problem.'
            Resolution = 'Run Get-ClusterGroup -Name <role> | Get-ClusterResource on a cluster node, inspect the failed resource and its first error, and coordinate the specific repair. Do not use the unsupported Get-ClusterResource -Group syntax. Starting a group changes workload state and requires owner approval. Verify intended resource and workload state afterwards.'
        }
    }
    # First match wins. Product thresholds are authored policy, not Microsoft recommendations.
    Profiles = @(
        @{
            Id = 'cluster-roles'; Match = '\.Cluster\.Group\.'
            Meaning = 'Clustered role failure and retry evidence. A role may contain several resources; locate the first failed dependency rather than treating every alert as a separate outage.'
            Diagnose = 'On the current owner, run Get-ClusterGroup and pipe the affected group to Get-ClusterResource. Read the local System log provider Microsoft-Windows-FailoverClustering, including 1069, 1194, 1205 and 1254. Match named ResourceGroup and ResourceName fields, timestamp and error code. For VM configuration failures, compare VmId with Get-VM on every possible owner and verify the configuration path exists.'
            Repair = 'Restore the specific missing dependency with its owning team. A Network Name creation failure needs the directory team to validate the cluster name account, destination container permissions, quota and any prestaged virtual computer object. A missing VM configuration needs backup/storage and VMM inventory reconciliation. Remove an orphaned role only after its owner confirms retirement and recoverability. Do not repeatedly restart a role or increase failover thresholds to hide the cause.'
            Verify = 'Verify resources and intended workloads are online, new failure events stop, and native and SCOM leaf states recover. Failure-window monitors can remain elevated until old episodes age out. An intentionally stopped VM or empty Available Storage group is not by itself evidence of a cluster outage.'
            Links = @('https://learn.microsoft.com/en-us/windows-server/failover-clustering/prestage-cluster-adds','https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/hyper-v-start-state-access-failures-clustered-standalone')
        },
        @{
            Id = 'cluster-csv'; Match = '\.Cluster\.CSV\.'
            Meaning = 'Cluster Shared Volume accessibility, capacity or I/O pressure, as observed by the cluster collector; worst-volume metrics summarize multiple CSVs.'
            Diagnose = 'Run Get-ClusterSharedVolume and inspect SharedVolumeInfo, owner, state and partition free space for each volume. Correlate redirected or paused access with backup activity, storage-path health, System events and CSV performance samples. Compare all nodes before assuming the coordinator is the failing storage device.'
            Repair = 'For unexpected redirection or offline storage, restore the failed storage/network dependency with the storage team. For low free space, stop unapproved growth and plan supported capacity expansion or owner-approved cleanup. Never delete VHDX/AVHDX files or force storage online as a generic alert response.'
            Verify = 'Confirm every affected CSV is accessible from its intended nodes, expected direct access returns after maintenance, capacity headroom is restored, and latency stays below policy over a representative workload period.'
            Links = @('https://learn.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-manage-cluster-shared-volumes','https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/storage-issues-in-hyper-v-and-windows-server-failover-clusters')
        },
        @{
            Id = 'cluster'; Match = '\.Capability\.Cluster\.'
            Meaning = 'Cluster membership, quorum, witness, inter-node network or collector health. Loss of redundancy can precede an outage even while VMs remain running.'
            Diagnose = 'Run Get-ClusterNode, Get-ClusterQuorum and Get-ClusterNetwork locally on a cluster node. Identify paused versus down nodes, configured and current votes, witness state and partitioned networks. Review maintenance and the first cluster event. For collection errors, verify the supported Windows PowerShell runtime and FailoverClusters module before interpreting zero counts.'
            Repair = 'Restore the failed node, witness or network with the platform owner. Resume intentionally paused nodes only after maintenance is complete. Do not force quorum, change node weights or restart all nodes to clear a monitor. Repair collector access separately from workload health.'
            Verify = 'Confirm expected membership, quorum resilience and network state, then verify fresh collector results and the originating monitor before the parent DA.'
            Links = @('https://learn.microsoft.com/en-us/windows-server/failover-clustering/what-is-quorum-witness','https://learn.microsoft.com/en-us/windows-server/storage/storage-spaces/quorum','https://learn.microsoft.com/en-us/windows/win32/api/clusapi/nf-clusapi-pauseclusternode','https://learn.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-accounts-overview','https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/hyper-v-cluster-connectivity-management-configuration')
        },
        @{
            Id = 's2d'; Match = '\.Capability\.S2D\.'
            Meaning = 'Storage Spaces Direct pool, virtual disk, physical disk, cache, repair or Health Service evidence. Degraded resiliency and predictive drive faults deserve action before data becomes unavailable.'
            Diagnose = 'Inspect Get-StoragePool, Get-VirtualDisk, Get-PhysicalDisk and Get-StorageJob, recording both HealthStatus and OperationalStatus. Run Get-StorageSubSystem Cluster* | Debug-StorageSubSystem and retain the fault identifier, severity, reason, recommendation and physical location. Compare repair progress over time.'
            Repair = 'Follow the specific storage fault recommendation after confirming remaining resiliency and the correct physical device. Coordinate replacement, repair or expansion with the storage owner. Do not reset disks, remove pool members, change read-only flags or delete virtual disks as generic troubleshooting.'
            Verify = 'Confirm the fault disappears from native Health Service, repair progresses or completes, intended redundancy returns and free pool capacity remains adequate.'
            Links = @('https://learn.microsoft.com/en-us/windows-server/failover-clustering/health-service-faults','https://learn.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-states','https://learn.microsoft.com/en-us/windows-server/storage/storage-spaces/troubleshooting-storage-spaces')
        },
        @{
            Id = 'smb'; Match = '\.Capability\.FileServices\.'
            Meaning = 'Hyper-V storage over SMB: client/server participation, share and VHDX mappings, sessions, security policy, continuous availability, witness and multichannel resilience.'
            Diagnose = 'Identify the client host and exact server/share path. Inspect Get-SmbConnection, Get-SmbMultichannelConnection and the matching share on its server; compare negotiated signing, encryption and continuous-availability properties with policy. Correlate SMBClient/SMBServer event channels, latency and transport errors. A client-side test alone cannot prove the server service is stopped.'
            Repair = 'Restore the affected SMB service, path or network after impact review; correct share permissions and authentication with the file-services team. Preserve security requirements. Never enable SMB1, disable signing/encryption or disconnect all SMB sessions to make a monitor green.'
            Verify = 'Verify the intended share and VM disk are reachable, required security and redundancy are negotiated, errors stop and representative I/O recovers.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/troubleshoot-smb-guidance','https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/storage-issues-in-hyper-v-and-windows-server-failover-clusters')
        },
        @{
            Id = 'san'; Match = '\.Capability\.Storage\.'
            Meaning = 'Host-visible SAN LUNs, host attachments, iSCSI sessions, Fibre Channel ports and VM disk mappings. Host paths and array-side volume health are distinct sources.'
            Diagnose = 'Match stable disk/LUN and initiator identifiers before comparing Get-Disk, Get-IscsiSession, Get-IscsiConnection and MPIO path reports. For FC, retain HBA port identity and vendor driver counters. Correlate host System storage errors with switch zoning, masking and array events. Separate loss of one redundant path from complete I/O loss.'
            Repair = 'Restore the identified fabric path or approved MPIO configuration with the storage and network teams. Use compatible HBA/NIC/array firmware guidance. Capacity remediation needs array and filesystem planning. Do not initialize, format, offline or reset a shared disk, or remove active sessions, as generic remediation.'
            Verify = 'Confirm expected path count, stable sessions and LUN identity, normal I/O and recovered redundancy. Compare counter deltas after repair; historical cumulative counters may not reset.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/iscsi-storage-connectivity-troubleshooting','https://learn.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/troubleshoot-data-corruption-and-disk-errors')
        },
        @{
            Id = 'atc'; Match = '\.Capability\.NetworkATC\.'
            Meaning = 'Network ATC intent and per-node convergence/configuration evidence. This capability is applicable only where Network ATC owns the host network configuration.'
            Diagnose = 'Inspect Get-NetIntent and Get-NetIntentStatus on eligible nodes. Compare intent adapter membership, provisioning errors, node status and approved global overrides. Check adapter symmetry, link/RDMA readiness and switch DCB/PFC settings against the intent. Missing ATC on a manual or VMM-managed network is not itself an outage.'
            Repair = 'Resolve the precise convergence error through the selected network authority. Plan changes to intents and switch configuration together. Do not manually overwrite ATC-managed settings or enable ATC alongside a conflicting VMM/SDN authority merely to satisfy monitoring.'
            Verify = 'Verify intended nodes converge, effective configuration matches approved policy and no new apply failures occur after the normal convergence interval.'
            Links = @('https://learn.microsoft.com/en-us/windows-server/networking/network-atc/manage-network-atc','https://learn.microsoft.com/en-us/powershell/module/networkatc/get-netintentstatus?view=windowsserver2025-ps')
        },
        @{
            Id = 'sdn'; Match = '\.Capability\.SDN\.'
            Meaning = 'Software-defined networking control-plane, host binding, data-plane and certificate evidence. Control-plane failure does not prove every existing tenant flow has failed.'
            Diagnose = 'Identify the controller, host and tenant path involved. Inspect the reported service, host identifier, listener, controller connectivity and VFP extension before changing anything. For certificates, record subject, issuer, validity, chain and intended binding without exporting private keys. Correlate policy/configuration errors with the native controller and host logs.'
            Repair = 'Correct the specific controller/host policy, connectivity or certificate binding through the SDN authority. Renew certificates before expiry using the deployment-specific procedure. Do not disable certificate validation, remove VFP extensions or restart the entire controller cluster as a generic fix.'
            Verify = 'Confirm controller and host agreement, trusted unexpired certificates, cessation of fresh errors and a representative tenant-path test. Follow Security health through the DA separately from availability.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/software-defined-networking/troubleshoot-sdn-guidance','https://learn.microsoft.com/en-us/troubleshoot/windows-server/software-defined-networking/troubleshoot-windows-server-software-defined-networking-stack')
        },
        @{
            Id = 'vmm'; Match = '\.Capability\.VMM\.'
            Meaning = 'VMM management, host agents, jobs, clouds and network configuration. Cloud quota exhaustion is not necessarily physical-cluster resource exhaustion; inspect the named constrained dimension.'
            Diagnose = 'Use the matching read-only VMM task and native Jobs/Fabric/Clouds views. Capture the failing job ID and inner error, host agent status/version, configured cloud limit and consumed value, or exact logical network/site/uplink binding. Verify the VMM Run As account and supported module runtime for query failures.'
            Repair = 'Resolve the reported inner job or communication error. Coordinate agent updates with the VMM upgrade baseline. Change cloud quotas only after confirming physical headroom and tenant policy. Correct missing network sites or uplink mappings through VMM, not by ad hoc host-side changes. Do not rerun mutating failed jobs without checking partial completion.'
            Verify = 'Confirm fresh VMM queries, expected host status, valid network bindings and quota headroom. Recent-failure monitors may remain unhealthy until their lookback window expires even after successful new jobs.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/system-center/vmm/troubleshoot-host-status-errors','https://learn.microsoft.com/en-us/system-center/vmm/upgrade-vmm?view=sc-vmm-2025','https://learn.microsoft.com/en-us/system-center/vmm/self-service?view=sc-vmm-2025','https://learn.microsoft.com/en-us/system-center/vmm/network-logical?view=sc-vmm-2025','https://learn.microsoft.com/en-us/system-center/vmm/manage-networks?view=sc-vmm-2025')
        },
        @{
            Id = 'replica'; Match = 'Replication|Replica'
            Meaning = 'Host-observed replication state and disaster-recovery protection, not an application availability test inside the guest.'
            Diagnose = 'Use Get-VMReplication and Measure-VMReplication for the named VM on its owner. Inspect replication mode, primary/replica server, health, last replication time and backlog. For a cluster broker, follow network-name and broker resource dependencies. Distinguish planned pause, initial replication and unexpected loss of protection.'
            Repair = 'Restore the actual authentication, certificate, broker, network or storage dependency. Coordinate resume or resynchronization with the recovery owner and verify bandwidth/storage impact. Never perform failover, reverse replication or remove/recreate protection solely to clear an alert.'
            Verify = 'Confirm replication resumes and lag meets the agreed recovery-point objective. A healthy running primary VM alone does not establish healthy disaster recovery.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/hyper-v-replica-troubleshooting-guide')
        },
        @{
            Id = 'guest-integration'; Match = 'Heartbeat|IntegrationServices'
            Meaning = 'Hyper-V host-to-guest integration channel evidence. No guest SCOM agent is required, and this signal does not prove application health inside the VM.'
            Diagnose = 'On the current VM owner inspect Get-VMIntegrationService for the exact VM and its expected power state. Distinguish a disabled integration service, unsupported guest, starting guest and an unresponsive running guest. Engage the guest owner for guest-side service/log checks.'
            Repair = 'Correct integration-service policy or supported guest components with the workload owner. Do not restart a guest or install a SCOM agent to satisfy this host-based monitor without separate authorization.'
            Verify = 'Confirm the configured integration service reports its expected status and host-side monitoring recovers; validate application service separately through its own owner.'
            Links = @('https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-integration-services')
        },
        @{
            Id = 'directory'; Match = 'DomainHealth|ActiveDirectory'
            Meaning = 'Host-observed domain and secure-channel dependency, not an exhaustive domain-controller replication or AD health assessment.'
            Diagnose = 'Run the read-only domain diagnostic from the affected host. Verify DNS/DC discovery, time synchronization, network reachability and Test-ComputerSecureChannel without -Repair. Correlate NETLOGON errors with directory-team evidence.'
            Repair = 'Restore DNS/time/connectivity first where indicated. If the machine account trust is genuinely broken, use the approved directory recovery procedure with the AD owner. Do not unjoin/rejoin a clustered host or reset machine passwords as a first response.'
            Verify = 'Repeat the secure-channel and domain discovery checks, verify normal authentication and fresh monitor recovery.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-security/broken-trust-relationship-domain-joined-device-its-domain-secure-channel-issues')
        },
        @{
            Id = 'dns'; Match = 'Dns'
            Meaning = 'DNS service or name-resolution dependency as tested by the configured probe, not proof that every zone or client is healthy.'
            Diagnose = 'Run the DNS diagnostic on the affected host. Record queried name/type, configured resolver, response/error and forward/SRV results. Compare another resolver and another client to distinguish client configuration, path and authoritative-server failures.'
            Repair = 'Correct the proven resolver, zone, record, forwarding or network issue with the DNS owner. Avoid global cache flushes or DNS-service restarts without a specific reason.'
            Verify = 'Repeat the same failing query from the original host and confirm fresh monitoring evidence, not merely a cached successful answer from another machine.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/troubleshoot-dns-guidance','https://learn.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/troubleshoot-dns-server')
        },
        @{
            Id = 'dhcp'; Match = 'Dhcp'
            Meaning = 'Configured DHCP service reachability/health evidence. This is not an exhaustive lease, scope or client transaction monitor unless the leaf explicitly measures those facts.'
            Diagnose = 'Check the named DHCP endpoint, service status, authorization, applicable scope free leases and relay path with the DHCP owner. Compare a client on the server subnet with one behind the affected relay.'
            Repair = 'Correct the proven service, scope or relay issue through approved network change control. Do not authorize unknown DHCP servers or change scope ranges to clear a reachability alarm.'
            Verify = 'Confirm the configured probe and a representative lease transaction recover without address conflicts.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/troubleshoot-dhcp-guidance')
        },
        @{
            Id = 'performance'; Match = 'Cpu|Processor|Memory|Paging|PagesPressure|Latency|QueueDepth|QueueLength|NetworkUtilization|NetworkErrors'
            Meaning = 'Measured resource pressure or I/O delay. A warning is an opportunity to investigate headroom; a threshold crossing alone does not identify the defective component or predict a failure time.'
            Diagnose = 'Record the named counter, measured value, units, sampling interval and effective thresholds. Compare a representative time series with workload changes, host placement and storage/network evidence. Separate host/root/guest CPU and assigned/demanded memory. Missing counters are a telemetry problem, not zero utilization.'
            Repair = 'Address the identified contention, workload placement or failing path with its owner. Capacity changes require a headroom and failover-reserve check. Do not blindly increase thresholds, reboot hosts or reduce VM resources to suppress symptoms.'
            Verify = 'Observe the same metric over a representative load period, confirm sustained recovery and verify workload response independently. Product defaults require site-specific review and are not Microsoft service-level guarantees.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/troubleshoot-hyper-v-virtual-machine-performance')
        },
        @{
            Id = 'pipeline'; Match = 'Pipeline|PowerShell|IntegrationHealth|CapabilityHealth|MonitoringComponent'
            Meaning = 'Monitoring capability, data collection or freshness. Failure means visibility is impaired; do not infer that the monitored workload itself is down or healthy.'
            Diagnose = 'Read the first probe error and Operations Manager event context. Verify HealthService availability, supported PowerShell runtime, required modules, Run As scope and agent proxy where cross-object discovery requires it. Compare last successful sample and discovery time.'
            Repair = 'Correct the missing runtime/module, access or source defect. Preserve logs before any approved HealthService restart. Do not reset health or clear the agent cache as a substitute for understanding a repeatable script error.'
            Verify = 'Require a new successful discovery/sample and initialized leaf monitors. Old green values cannot establish recovery of a broken collector.'
            Links = @('https://learn.microsoft.com/en-us/system-center/scom/manage-consoles-overview-healthexplorer?view=sc-om-2025')
        },
        @{
            Id = 'network'; Match = 'PhysicalNetwork|VirtualSwitch|Network|TopOfRack|OutOfBand|EdgeFirewall|ConsoleServer|PhysicalChassis|PureStorage'
            Meaning = 'Host network or external infrastructure evidence at the precise scope of the leaf. TCP reachability is not device hardware, firewall-policy or application health; linked vendor monitors retain their own authority.'
            Diagnose = 'Identify the adapter, switch, port or configured endpoint and the actual observation source. Compare link state, negotiated speed and error/discard deltas with device-side evidence. Check routing and the intended port from the collector. An unreachable management endpoint does not by itself prove the data plane failed.'
            Repair = 'Restore the specific path, cable/optic, approved switch configuration or device service with the network/hardware owner. Consult the vendor for proprietary device faults. Do not disable security controls, bounce all uplinks or reboot management devices based only on a failed TCP probe.'
            Verify = 'Repeat the original path test and confirm relevant native/vendor health. For cumulative errors, observe new deltas; do not expect historic totals to disappear.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/troubleshoot-tcp-ip-communication-guidance')
        },
        @{
            Id = 'virtualization'; Match = 'VmRuntime|VirtualMachine|VirtualHardDisk|Host\.|HostRole|DeploymentService|StorageAttachments|Checkpoints'
            Meaning = 'Host-based Hyper-V workload or management evidence. A stopped VM must be compared with its intended state; inventory presence is not guest application monitoring.'
            Diagnose = 'Run the matching read-only host/VM task. Match the stable VM ID and current owner, inspect Get-VM, attached disks, checkpoint chain and Hyper-V-VMMS/High-Availability logs. For management-service errors verify the named service and first failure rather than assuming every guest stopped.'
            Repair = 'Restore the identified service, configuration, storage or VM dependency with the workload owner. Check intended shutdown and maintenance policy first. Never delete checkpoint files, force power operations or restart VMMS/hosts solely to clear an alert.'
            Verify = 'Confirm the intended VM/service state, fresh host-derived evidence and the originating monitor. Guest application recovery requires a separate workload-level check.'
            Links = @('https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/hyper-v-start-state-access-failures-clustered-standalone','https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/hyper-v-virtual-machine-backup-checkpoint-storage')
        },
        @{
            Id = 'topology'; Match = '.*'
            Meaning = 'A discovered identity, logical boundary, component group or health dependency in the private-cloud service model. Containment draws a diagram; only authored monitors and health dependencies determine its health.'
            Diagnose = 'Open Health Explorer from the unhealthy DA, follow the failing health aspect and dependency to the named leaf object, and read its state-change context and knowledge. Check whether the object is an inventory-only reference or an authoritative monitor target. Record the complete root-to-leaf path.'
            Repair = 'Repair the originating leaf condition using its specific runbook and owner. Do not reset or edit a parent DA to conceal child health. Missing relationships or wrong aspect routing require a source change, tests and a new sealed MP version.'
            Verify = 'Confirm fresh healthy leaf evidence and follow recovery through each dependency back to the solution root. Unknown/unmonitored objects and absent optional capabilities must not be described as fully monitored healthy services.'
            Links = @('https://learn.microsoft.com/en-us/system-center/scom/manage-consoles-overview-healthexplorer?view=sc-om-2025')
        }
    )
}
